import Head from "next/head";
import { Chat } from "../components/chat/chat";
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import { setConstantValue } from "typescript";
import { useState } from "react";

const firebaseConfig = {
  apiKey: "AIzaSyD37qlyAef_2lwMrw29QSy4pybUUCCKcto",
  authDomain: "chat-app-a7ade.firebaseapp.com",
  projectId: "chat-app-a7ade",
  storageBucket: "chat-app-a7ade.appspot.com",
  messagingSenderId: "219994442628",
  appId: "1:219994442628:web:a23c8b71330df3f0fbebd1",
  measurementId: "G-8NT4LSEY1E"

};

const app = firebase.initializeApp(firebaseConfig);
let currentUser: firebase.User | null = null;

firebase.auth().onAuthStateChanged((user) => {
  currentUser = user;
})

let loggedIn: boolean = false;

if (currentUser) {
  loggedIn = true
} else {
  loggedIn = false
}

const provider = new GoogleAuthProvider()

function SignIn() {
  const auth = getAuth();
  const handleClick = () => {
    signInWithPopup(auth, provider)
  }

  return (
    <div>
      <button onClick={handleClick}>Sign in</button>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>chat-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <section>{loggedIn ? <Chat /> : <SignIn />}</section>
      </main>
    </>
  );
}
